# Generated by Django 3.2.9 on 2022-02-27 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozisaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funsionariu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=200, null=True)),
                ('seksu', models.CharField(choices=[('Feto', 'Feto'), ('Mane', 'Mane')], max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('nu_telefone', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('Aldeia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia')),
                ('administrativepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality')),
                ('pozisaun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsionariu.pozisaun')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village')),
            ],
        ),
    ]
