# Generated by Django 3.2.9 on 2022-04-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0002_userfunsionariu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funsionariu',
            old_name='Aldeia',
            new_name='aldeia',
        ),
    ]
