# Generated by Django 3.2.9 on 2022-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0004_auto_20220417_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='funsionariu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='funsionariu'),
        ),
    ]
