# Generated by Django 3.2.9 on 2022-04-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0005_funsionariu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funsionariu',
            name='tipu_f',
            field=models.CharField(blank=True, choices=[('Dir', 'Diretor'), ('Fun', 'Funsionariu'), ('EIP', 'Ekipa Implementasaun Programa')], max_length=30, null=True),
        ),
    ]
