# Generated by Django 3.2.9 on 2022-04-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('funsionariu', '0006_alter_funsionariu_tipu_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funsionariu',
            name='aldeia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia'),
        ),
    ]
