# Generated by Django 3.1.1 on 2022-01-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20220105_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funsionariu',
            old_name='hela_fatin',
            new_name='aldeia',
        ),
        migrations.AddField(
            model_name='funsionariu',
            name='postu',
            field=models.CharField(choices=[('Postu Administrativu Atauro', 'Postu Administrativu Atauro'), ('Postu Administrativu Cristo rei', 'Postu Administrativu Cristo rei'), ('Postu Administrativu Dom Aleixo', 'Postu Administrativu Dom Aleixo'), ('Postu Administrativu Metinaru', 'Postu Administrativu Metinaru'), ('Postu Administrativu Nain Feto', 'Postu Administrativu Nain Feto'), ('Postu Administrativu Vera-Cruz', 'Postu Administrativu Vera-Cruz')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funsionariu',
            name='suku',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funsionariu',
            name='pozisaun',
            field=models.CharField(choices=[('Ekipa Jestaun Suku (EIP)', 'Ekipa Jestaun Suku (EIP)'), ('Fasilitador Tekniku Postu Administrativu Atauro', 'Fasilitador Tekniku Postu Administrativu Atauro'), ('Fasilitador Tekniku Postu Administrativu Cristo rei', 'Fasilitador Tekniku Postu Administrativu Cristo rei'), ('Fasilitador Tekniku Postu Administrativu Dom Aleixo', 'Fasilitador Tekniku Postu Administrativu Dom Aleixo'), ('Fasilitador Tekniku Postu Administrativu Metinaru', 'Fasilitador Tekniku Postu Administrativu Metinaru'), ('Fasilitador Tekniku Postu Administrativu Nain Feto', 'Fasilitador Tekniku Postu Administrativu Nain Feto'), ('Fasilitador Tekniku Postu Administrativu Vera-Cruz', 'Fasilitador Tekniku Postu Administrativu Vera-Cruz'), ('Direktor', 'Direktor')], max_length=200, null=True),
        ),
    ]
