# Generated by Django 3.1.1 on 2022-01-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20220105_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(choices=[('Bee mos', 'Bee mos'), ('Uma Kbiit Laek', 'Uma Kbiit Laek'), ('Hadia Estrada', 'Hadia Estrada'), ('Moru', 'Moru')], max_length=200, null=True)),
                ('sistema_implementasaun', models.CharField(choices=[('Bee mos', 'Bee mos'), ('Irigasaun', 'Irigasaun'), ('Reservoir', 'Reservoir'), ('Gravitasaun', 'Gravitasaun'), ('Drenajen', 'Drenajen'), ('Akaptasaun', 'Akaptasaun')], max_length=200, null=True)),
                ('funsionariu', models.CharField(max_length=200, null=True)),
                ('postu', models.CharField(choices=[('Postu Administrativu Atauro', 'Postu Administrativu Atauro'), ('Postu Administrativu Cristo rei', 'Postu Administrativu Cristo rei'), ('Postu Administrativu Dom Aleixo', 'Postu Administrativu Dom Aleixo'), ('Postu Administrativu Metinaru', 'Postu Administrativu Metinaru'), ('Postu Administrativu Nain Feto', 'Postu Administrativu Nain Feto'), ('Postu Administrativu Vera-Cruz', 'Postu Administrativu Vera-Cruz')], max_length=200, null=True)),
                ('suku', models.CharField(max_length=200, null=True)),
                ('aldeia', models.CharField(max_length=200, null=True)),
                ('pursentu_programa', models.CharField(max_length=200, null=True)),
                ('orsamentu_gastu', models.FloatField(null=True)),
                ('partisipasun_feto', models.CharField(max_length=200, null=True)),
                ('ekipamentu_lakompletu', models.CharField(max_length=200, null=True)),
                ('komentariu', models.CharField(max_length=200, null=True)),
                ('date_monitoring', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(choices=[('Bee mos', 'Bee mos'), ('Uma Kbiit Laek', 'Uma Kbiit Laek'), ('Hadia Estrada', 'Hadia Estrada'), ('Moru', 'Moru')], max_length=200, null=True)),
                ('sistema_implementasaun', models.CharField(choices=[('Bee mos', 'Bee mos'), ('Irigasaun', 'Irigasaun'), ('Reservoir', 'Reservoir'), ('Gravitasaun', 'Gravitasaun'), ('Drenajen', 'Drenajen'), ('Akaptasaun', 'Akaptasaun')], max_length=200, null=True)),
                ('postu', models.CharField(choices=[('Postu Administrativu Atauro', 'Postu Administrativu Atauro'), ('Postu Administrativu Cristo rei', 'Postu Administrativu Cristo rei'), ('Postu Administrativu Dom Aleixo', 'Postu Administrativu Dom Aleixo'), ('Postu Administrativu Metinaru', 'Postu Administrativu Metinaru'), ('Postu Administrativu Nain Feto', 'Postu Administrativu Nain Feto'), ('Postu Administrativu Vera-Cruz', 'Postu Administrativu Vera-Cruz')], max_length=200, null=True)),
                ('suku', models.CharField(max_length=200, null=True)),
                ('aldeia', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
