# Generated by Django 3.1.1 on 2022-01-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_monitoring_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='pursentu_programa',
            field=models.FloatField(null=True),
        ),
    ]
