# Generated by Django 3.1.1 on 2022-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20220105_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='programa',
            name='sistema_implementasaun',
        ),
        migrations.AddField(
            model_name='programa',
            name='tags',
            field=models.ManyToManyField(to='monitoring.Tag'),
        ),
    ]
