# Generated by Django 3.1.1 on 2022-01-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20220105_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistema',
            old_name='naran',
            new_name='naran_sist',
        ),
    ]
