# Generated by Django 3.1.1 on 2022-01-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20220105_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='funsionariu',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='programa',
        ),
    ]
