# Generated by Django 3.1.1 on 2022-01-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_auto_20220105_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='data_monitoring',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='faze',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='siklu',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
