# Generated by Django 3.1.1 on 2022-01-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_auto_20220105_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='faze',
            field=models.CharField(choices=[('Dahuluk I', 'Dahuluk I'), ('Daruak II', 'Daruak II'), ('Datoluk III', 'Datoluk III'), ('Dahaat IV', 'Dahaat IV'), ('Dalima V', 'Dalima V'), ('Daneen VI', 'Daneen VI'), ('Dahitu VII', 'Dahitu VII')], max_length=200, null=True),
        ),
    ]
