# Generated by Django 3.1.1 on 2022-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_auto_20220105_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postu', models.CharField(choices=[('Postu Administrativu Atauro', 'Postu Administrativu Atauro'), ('Postu Administrativu Cristo rei', 'Postu Administrativu Cristo rei'), ('Postu Administrativu Dom Aleixo', 'Postu Administrativu Dom Aleixo'), ('Postu Administrativu Metinaru', 'Postu Administrativu Metinaru'), ('Postu Administrativu Nain Feto', 'Postu Administrativu Nain Feto'), ('Postu Administrativu Vera-Cruz', 'Postu Administrativu Vera-Cruz')], max_length=200, null=True)),
                ('naran_suku', models.CharField(choices=[('Beloi ', 'Beloi '), ('Bikeli ', 'Bikeli '), ('Makadade ', 'Makadade '), ('Makili ', 'Makili '), ('Vila Maumeta ', 'Vila Maumeta '), ('Ailok ', 'Ailok '), ('Balibar ', 'Balibar '), ('Becora ', ' Becora '), ('Bidau Santana ', ' Bidau Santana '), ('Camea', ' Camea '), ('Kulu hun  ', ' Kulu hun '), ('Hera ', 'Hera '), ('Metiaut ', ' Metiaut '), ('Bairo Pite ', 'Bairo Pite '), ('Bebonuk ', 'Bebonuk '), ('Comoro ', ' Comoro '), ('Fatuhada ', ' Fatuhada '), ('Kampung Alor', ' Kampung Alor '), ('Madohi ', ' Madohi '), ('Manleuana ', 'Manleuana '), ('Mantelolau ', 'Mantelolau '), ('Sabuli ', 'Sabuli '), ('Benunuk', ' Benunuk '), ('Akadiru hun ', ' Akadiru hun '), ('Bemori', 'Bemori '), (' Bidau Lecidere ', ' Bidau Lecidere '), ('Gricenfor ', 'Gricenfor '), (' Lahane Oriental ', ' Lahane Oriental '), ('Santa Cruz ', 'Santa Cruz '), ('Kaikoli ', ' Kaikoli '), ('Kolmera', ' Kolmera '), (' Dare ', ' Dare '), ('Lahane Ocidental', ' Lahane Ocidental '), (' Mascarenhas ', ' Mascarenhas '), ('Motael ', 'Motael '), (' Vila Verde ', 'Vila Verde')], max_length=200, null=True)),
                ('status_bee', models.CharField(choices=[('Asesu Bee ona', 'Asesu Bee ona'), ('Seidauk Asesu Bee', 'Seidauk Asesu Bee ')], max_length=100, null=True)),
                ('status_monitoring', models.CharField(choices=[('Monitoring ona', 'Monitoring ona'), ('Seidauk Monitoring', 'Seidauk Monitoring')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='suku',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='suku',
            field=models.ManyToManyField(to='monitoring.Suku'),
        ),
    ]
