# Generated by Django 3.1.1 on 2022-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_monitoring_status_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='pursentu_programa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
