# Generated by Django 3.1.1 on 2022-01-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_auto_20220108_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='data_monitoring',
        ),
    ]
