# Generated by Django 3.1.1 on 2022-01-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_remove_monitoring_data_monitoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='sistema',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='sistema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.sistema'),
        ),
    ]
