# Generated by Django 3.1.1 on 2022-01-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_auto_20220117_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoring',
            old_name='sistema',
            new_name='sistem',
        ),
    ]
