# Generated by Django 3.1.1 on 2022-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_auto_20220117_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='status_bee',
            field=models.CharField(choices=[('Asesu Bee ona', 'Asesu Bee ona'), ('Seidauk Asesu Bee', 'Seidauk Asesu Bee ')], max_length=100, null=True),
        ),
    ]
