# Generated by Django 3.1.1 on 2022-01-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_monitoring_status_bee'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='status_monitor',
            field=models.CharField(choices=[('Monitoring ona', 'Monitoring ona'), ('Seidauk Monitoring', 'Seidauk Monitoring')], max_length=100, null=True),
        ),
    ]
