# Generated by Django 3.1.1 on 2022-01-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_monitoring_status_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='status_monitor',
        ),
    ]
