# Generated by Django 3.2.9 on 2022-02-27 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_auto_20220228_0241'),
        ('funsionariu', '0001_initial'),
        ('programa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postimplementationmonitoring',
            name='implementasaun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.implementasaun'),
        ),
        migrations.AddField(
            model_name='postimplementationmonitoring',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='funsionariu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funsionariu.funsionariu'),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='implementasaun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.implementasaun'),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
