# Generated by Django 3.2.9 on 2022-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_auto_20220228_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postimplementationmonitoring',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
