# Generated by Django 3.2.9 on 2022-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_auto_20220417_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationmonitoring',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Monitoring'),
        ),
        migrations.AddField(
            model_name='postimplementationmonitoring',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PostMonitoring'),
        ),
    ]
