# Generated by Django 3.2.9 on 2022-04-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_auto_20220417_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationmonitoring',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='is_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='postimplementationmonitoring',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='postimplementationmonitoring',
            name='is_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='postimplementationmonitoring',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
