# Generated by Django 3.2.9 on 2022-04-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0008_auto_20220419_1946'),
        ('monitoring', '0028_auto_20220418_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationmonitoring',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='rejected_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimplementationmonitoring',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='postimplementationmonitoring',
            name='rejected_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='implementasaun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implementasaun', to='programa.implementasaun'),
        ),
        migrations.AlterField(
            model_name='postimplementationmonitoring',
            name='implementasaun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postImplementasaun', to='programa.implementasaun'),
        ),
    ]
