# Generated by Django 3.2.9 on 2022-05-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_auto_20220420_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementationmonitoring',
            name='partisipasaun_feto',
        ),
        migrations.RemoveField(
            model_name='implementationmonitoring',
            name='statusImplementasaun',
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='orsamentu_acumulativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orsamentu Acumulativa'),
        ),
        migrations.AddField(
            model_name='implementationmonitoring',
            name='pursentu_acumulativa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pursentu Acumulativa'),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='orsamentu_gastu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orsamentu Gastus'),
        ),
        migrations.AlterField(
            model_name='implementationmonitoring',
            name='pursentu_programa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pursentu Implementasaun'),
        ),
    ]
