# Generated by Django 3.2.9 on 2022-05-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_implemented',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
