# Generated by Django 3.2.9 on 2022-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_alter_implementasaun_statusimplementasaun'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementasaun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ImplementasaunPrograma'),
        ),
    ]
