# Generated by Django 3.2.9 on 2022-04-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0005_auto_20220418_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementasaunpoint',
            name='implementasaun',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implementationLocation', to='programa.implementasaun'),
        ),
    ]
