# Generated by Django 3.2.9 on 2022-04-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0006_alter_implementasaunpoint_implementasaun'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementasaun',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='implementasaun',
            name='is_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='implementasaun',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
