# Generated by Django 3.2.9 on 2022-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0007_auto_20220418_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementasaun',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementasaun',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='implementasaun',
            name='rejected_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
