# Generated by Django 3.2.9 on 2022-05-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0008_auto_20220419_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementasaun',
            name='partisipasaunF',
            field=models.IntegerField(null=True, verbose_name='Partisipasaun Feto'),
        ),
        migrations.AddField(
            model_name='implementasaun',
            name='partisipasaunM',
            field=models.IntegerField(null=True, verbose_name='Partisipasaun Mane'),
        ),
        migrations.AddField(
            model_name='implementasaun',
            name='partisipasaunP',
            field=models.IntegerField(null=True, verbose_name='Partisipasaun Populasaun'),
        ),
    ]
