# Generated by Django 3.2.9 on 2022-05-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_is_implemented'),
        ('programa', '0010_auto_20220508_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementasaun',
            name='survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.survey'),
        ),
    ]
