# Generated by Django 3.2.9 on 2022-05-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0013_alter_implementasaun_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implementasaun',
            old_name='date',
            new_name='enddate',
        ),
        migrations.AddField(
            model_name='implementasaun',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
